#This Compose file is used for development purposes only. This can be edited on a local machine to test Airflow.

version: '3.7'

networks:
  airflow:
    name: airflow
    attachable: true

volumes:
  pgdata: {}
  logs: {}

x-database-env: 
  &database-env
  POSTGRES_USER: airflow
  POSTGRES_DB: airflow
  POSTGRES_PASSWORD: airflow
  POSTGRES_HOST: postgres
  POSTGRES_PORT: 5432

x-airflow-env: 
  &airflow-env
  AIRFLOW__CORE__EXECUTOR: CeleryExecutor
  AIRFLOW__WEBSERVER__RBAC: 'True'
  AIRFLOW__CORE__CHECK_SLAS: 'False'
  AIRFLOW__CORE__STORE_SERIALIZED_DAGS: 'True'
  AIRFLOW__CORE__STORE_DAG_CODE: 'True'
  AIRFLOW__CORE__PARALLELISM: 25
  AIRFLOW__CORE__LOAD_EXAMPLES: 'False'
  AIRFLOW__CORE__LOAD_DEFAULT_CONNECTIONS: 'False'
  AIRFLOW__SCHEDULER__SCHEDULER_HEARTBEAT_SEC: 10
  ADMIN_USER: airflow
  ADMIN_PASSWORD: airflow

services:
  postgres:
    image: postgres:12.2
    environment:
      <<: *database-env
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    command: >
     postgres
       -c listen_addresses=*
       -c logging_collector=on
       -c log_destination=stderr
       -c max_connections=50
    networks:
      - airflow

  redis:
    image: redis:5.0.9
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - 6379:6379
    networks:
      - airflow

  webserver:
    image: airflow:development
    ports:
      - 8080:8080
    volumes:
      - ./dags:/opt/airflow/dags
      - ./plugins:/opt/airflow/plugins
      - logs:/opt/airflow/logs
    environment:
      <<: *database-env
      <<: *airflow-env
    depends_on:
      - postgres
      - redis
    command: webserver
    healthcheck:
      test: ["CMD-SHELL", "[ -f /opt/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      - airflow

  flower:
    image: airflow:development
    ports:
      - 5555:5555
    environment:
      <<: *database-env
    volumes:
      - ./dags:/opt/airflow/dags
      - ./plugins:/opt/airflow/plugins
      - logs:/opt/airflow/logs
    command: flower
    depends_on:
      - redis
    networks:
      - airflow

  scheduler:
    image: airflow:development
    volumes:
      - ./dags:/opt/airflow/dags
      - ./plugins:/opt/airflow/plugins
      - logs:/opt/airflow/logs
    environment:
      <<: *database-env
      <<: *airflow-env
    command: scheduler
    depends_on:
      - postgres
    networks:
      - airflow

  worker:
    image: airflow:development
    volumes:
      - ./dags:/opt/airflow/dags
      - ./plugins:/opt/airflow/plugins
      - logs:/opt/airflow/logs
    environment:
      <<: *database-env
      <<: *airflow-env
    command: worker
    depends_on:
      - scheduler
    networks:
      - airflow
